# Rename all underscore-separated names to camelCase
# Ordered from longest to shortest to prevent partial matches

# Multi-word compound names (longest first)
s/Reporting_Relationship_Type/ReportingRelationshipType/g
s/performance_Indicator_Type/performanceIndicatorType/g
s/Performance_Indicator_Type/PerformanceIndicatorType/g
s/sub_Organization_Units/subOrganizationUnits/g
s/Organization_Unit_Mission/OrganizationUnitMission/g
s/Organization_Unit_Vision/OrganizationUnitVision/g
s/Service_Level_Agreements/ServiceLevelAgreements/g
s/service_Level_Target/serviceLevelTarget/g
s/Process_Responsibilities/ProcessResponsibilities/g
s/Service_Accountabilities/ServiceAccountabilities/g
s/Organization_Unit_Type/OrganizationUnitType/g
s/achieved_Service_Level/achievedServiceLevel/g
s/accountable_Role_Type/accountableRoleType/g
s/accountable_allocation_/accountableAllocation/g
s/Accountability_Element/AccountabilityElement/g
s/planned_Volume_Count/plannedVolumeCount/g
s/actual_Volume_Count/actualVolumeCount/g
s/Resource_Authorities/ResourceAuthorities/g
s/Performance_Indicator/PerformanceIndicator/g
s/volume_Period_Start/volumePeriodStart/g
s/planned_Performance/plannedPerformance/g
s/performance_Target/performanceTarget/g
s/Accountable_Element/AccountableElement/g
s/Deliverable_Element/DeliverableElement/g
s/service_Output_type/serviceOutputType/g
s/Service_Output_Type/ServiceOutputType/g
s/resource_Processes/resourceProcesses/g
s/planned_Client_Set/plannedClientSet/g
s/actual_Performance/actualPerformance/g
s/Assessable_Element/AssessableElement/g
s/Impcatable_Element/ImpcatableElement/g
s/change_Driver_Type/changeDriverType/g
s/Change_Driver_Type/ChangeDriverType/g
s/is_formal_Program/isFormalProgram/g
s/process_Level_Type/processLevelType/g
s/Proces_Level_Type/ProcesLevelType/g
s/Program_Class_Type/ProgramClassType/g
s/served_Client_Set/servedClientSet/g
s/sub_Target_Groups/subTargetGroups/g
s/client_set_Takeup/clientSetTakeup/g
s/Locatable_Element/LocatableElement/g
s/volume_Period_end/volumePeriodEnd/g
s/target_Group_Type/targetGroupType/g
s/Target_Group_Type/TargetGroupType/g
s/Organization_Unit/OrganizationUnit/g
s/Impact_Assessment/ImpactAssessment/g
s/impact_Receiver/impactReceiver/g
s/client_Indicator/clientIndicator/g
s/beneficiary_Rank/beneficiaryRank/g
s/Business_Process/BusinessProcess/g
s/Output_Producer/OutputProducer/g
s/Service_Impacts/ServiceImpacts/g
s/Resource_Impacts/ResourceImpacts/g
s/Program_Impacts/ProgramImpacts/g
s/Process_Impacts/ProcessImpacts/g
s/population_Size/populationSize/g
s/needs_Category/needsCategory/g
s/Needs_Category/NeedsCategory/g
s/achieved_Level/achievedLevel/g
s/program_Vision/programVision/g
s/sub_Processes/subProcesses/g
s/sub_Resources/subResources/g
s/Location_Type/LocationType/g
s/location_Type/locationType/g
s/Resource_Type/ResourceType/g
s/resource_Type/resourceType/g
s/Change_Driver/ChangeDriver/g
s/Service_Value/ServiceValue/g
s/program_Class/programClass/g
s/Service_Type/ServiceType/g
s/service_Type/serviceType/g
s/Process_Type/ProcessType/g
s/process_Type/processType/g
s/Program_Type/ProgramType/g
s/program_Type/programType/g
s/Project_Type/ProjectType/g
s/project_Type/projectType/g
s/impact_Level/impactLevel/g
s/target_Level/targetLevel/g
s/sub_Outcomes/subOutcomes/g
s/sub_Programs/subPrograms/g
s/sub_Services/subServices/g
s/Target_Group/TargetGroup/g
s/sub_Outputs/subOutputs/g
s/Status_Type/StatusType/g
s/Output_Type/OutputType/g
s/output_Type/outputType/g
s/sub_Needs/subNeeds/g
s/Role_Type/RoleType/g
s/role_Type/roleType/g
s/from_Date/fromDate/g
s/to_Date/toDate/g
